# This config file for Travis CI
sudo: required
dist: trusty
services:
  - docker
language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - levi.armstrong@swri.org
env:
  global:
    - TEST_BLACKLIST=bullet3_ros,fcl_ros,libccd_ros
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros              TEST=clang-format
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
